language: go
sudo: false

matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip

script:
  - go get -t -v ./...
