language: go

go:
  - '1.10.x'

services:
  - docker

before_install:
  - docker build -t vinchauhan/goiib .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master














