project: 
 modelVersion: "4.0.0"
 groupId: "com.springular.iib"
 artifactId: CustomerDatabaseV1
 version: "0.0.1-SNAPSHOT"
 packaging: bar
 profiles: 
  profile: 
   id: localdev
   activation: 
    activeByDefault: true
   properties: 
    workspace: "/artifacts/repo/"
    initialDeletes: "**/*.jar"
    unpackIibDependenciesIntoWorkspace: true
    failOnInvalidProperties: true
    useClassloaders: false
    failOnInvalidClassloader: true
    createOrPackageBar: create
    completeDeployment: true
    timeoutSecs: 600
    mqsiCreateBarDeployAsSource: true
  dependencies
    groupId: "com.springular.iib"
    artifactId: ErroHandling
    version: "0.0.1-SNAPSHOT"